### ISSUE TITLE
Is this what the diffs are supposed to look like?

### ISSUE THREAD

**Issue by kasbah** [guyzmo/eagle-automation#11]
Hey, thanks for working on these scripts.

I ran the difftool on [spark/core](https://github.com/spark/core) 
```
git difftool -t eaglediff v0.2.3..v0.2.4 -- EAGLE/core.brd
```
and this is what I got.

[OHqDfD_core-QEM11C_core.pdf](https://github.com/guyzmo/eagle-automation/files/676290/OHqDfD_core-QEM11C_core.pdf)
![ohqdfd_core-qem11c_core](https://cloud.githubusercontent.com/assets/206854/21531978/ec5a9b24-cd43-11e6-9ef9-d583c51a82e7.png)

Is this pretty much what is expected or is there something wrong with it? It did report an error at the end:

```
Traceback (most recent call last):
  File "./venv/bin/pea", line 11, in <module>
    sys.exit(main())
  File "./venv/lib/python3.5/site-packages/eagle_automation/pea.py", line 92, in main
    return eagle_automation.diff.diff_main(verbose=args['--verbose'])
  File "./venv/lib/python3.5/site-packages/eagle_automation/diff.py", line 219, in diff_main
    diff(args['<from-file>'], args['<to-file>'], int(args['--page'] if args['--page'] else 0), args['--output'])
  File "./venv/lib/python3.5/site-packages/eagle_automation/diff.py", line 203, in diff
    diff_visual(from_file, to_file, page, output)
  File "./venv/lib/python3.5/site-packages/eagle_automation/diff.py", line 183, in diff_visual
    workdir.cleanup()
AttributeError: 'str' object has no attribute 'cleanup'
```
 
Eagle is at 6.6, happy to upgrade to see if that helps.

**Comment by guyzmo** [comment]
I'm not doing much electronics work ATM, so I did not work with it recently, but yes this is mostly how it's supposed to look.

It's not aimed at being a thorough and perfectly readable diff like you'd expect for code, but only a way to help reviewing electronics work by targetting the places where the changes did happen.

AFAICT, it looks like you got several layers mixed up, and I was able to have one image per layer, though, to make it easier to view.

About the error, I think it's a legacy from old times, before the context manager was implemented and I was working with a `TemporaryDirectory` instance. That line can be safely removed. If you want to make a PR, I'll accept it happily ☺

**Comment by kasbah** [comment]
Ah yes, one diff per layer would work a lot better. Do you know why they are all diffed together for me?

**Comment by guyzmo** [comment]
If I remember it right, it should be a matter of [configuration](https://github.com/guyzmo/eagle-automation#configuration). Check the [configuration file example](https://github.com/guyzmo/eagle-automation/blob/master/skel/eagle_automation.conf).

There was also a trick to setup the PDF export parameters before using the diff tool to setup the size of the output (which cannot be configured by script), so maybe the exported layers can be set there as well…

I'm sorry to give you such a fuzzy answer, but it's been over a year I did not use that tool, and worked on many other projects since then ☺

Though, as imperfect that tool is, it really really helped me cope seamlessly with electronics engineering reviewing.

**Comment by kasbah** [comment]
Ok, fair enough. I'll play around with it. 

Personally I am interested in the diffs on a higher level as I am not actually an Eagle user. I was interested to see how useful they could be and think about putting something together that works on KiCAD or maybe Gerber files. 

You account of your usage of them is as valuable as trying it myself. Thanks very much!

**Comment by guyzmo** [comment]
well, with open formats being used by FLOSS tools like KiCAD, it might be possible to do a far better diff job, by using vectorized output you could isolate the changed elements along with a little context, cope with shifting of the design (if the EE moves the whole design by a few pixel, it will be impossible to see actual changes in the PDF diff), etc.

Also, reviewing changed on a board output is not as much important as looking at the schematic changes. I mean, for the board design, you need to check where changes happened, see if they have any mechanical impact on your project, and that's about all.

The real stuff to care about (and where 95% of the issues are) is in the schematic design, has that RC filter design been correctly patched? Have those I²C pull ups been added? etc.

**Comment by kasbah** [comment]
Yes, I think the "moving the whole design" would be problematic for schematics as well though.  Maybe diffs won't be truly useful unless things like [skidl](https://github.com/xesscorp/skidl) take off and schematics become code. :)
